// src/components/Shop/CollectionPreview.vue
<template>
    <article class="collection-preview">
        <h1 class="title">{{ collection.title }}</h1>
        <section class="preview">
            <CollectionItem v-for="item in items" :key="item.id" :item="item" />
        </section>
    </article>
</template>

<script>
import CollectionItem from '@/components/Shop/CollectionItem';

export default {
    name: 'CollectionPreview',
    components: {
        CollectionItem,
    },
    props: {
        collection: {
            type: Object,
            default: () => {},
        },
    },
    computed: {
        items() {
            return this.collection.items.filter((item, i) => i < 4);
        },
    },
};
</script>

<style lang="postcss" scoped>
.collection-preview {
    display: flex;
    flex-direction: column;
    margin-bottom: 30px;

    & .title {
        font-size: 28px;
        text-transform: uppercase;
        margin-bottom: 25px;
    }

    & .preview {
        display: flex;
        justify-content: space-between;
    }
}
</style>

// src/components/collection-preview/collection-preview.jsx
import React from "react";

import "./collection-preview.scss";
import CollectionItem from "../collection-item/collection-item";

const CollectionPreview = ({ title, items }) => (
  <article className="collection-preview">
    <h1 className="title">{title.toUpperCase()}</h1>
    <section className="preview">
      {items
        .filter((item, i) => i < 4)
        .map((item) => (
          <CollectionItem key={item.id} item={item} />
        ))}
    </section>
  </article>
);

export default CollectionPreview;
