// src/components/Shop/CollectionItem.vue
<template>
    <div class="collection-item">
        <div class="image" :style="{ backgroundImage: `url(${item.imageUrl})` }" />
        <footer class="collection-footer">
            <span class="name">{{ item.name }}</span>
            <span class="price">{{ item.price }}</span>
        </footer>
        <BaseButton inverted @click="$emit('click', item)">
            Add To Cart
        </BaseButton>
    </div>
</template>

<script>
import BaseButton from '@/components/Base/BaseButton';

export default {
    name: 'CollectionItem',
    components: {
        BaseButton,
    },
    props: {
        item: {
            type: Object,
            default: () => {},
        },
    },
};
</script>

<style lang="postcss" scoped>
.collection-item {
    width: 22%;
    display: flex;
    flex-direction: column;
    height: 350px;
    align-items: center;
    position: relative;

    & .image {
        width: 100%;
        height: 95%;
        background-size: cover;
        background-position: center;
        margin-bottom: 5px;
    }

    & .base-button {
        width: 80%;
        opacity: 0.7;
        position: absolute;
        top: 255px;
        display: none;
    }

    & .collection-footer {
        width: 100%;
        height: 5%;
        display: flex;
        justify-content: space-between;
        font-size: 18px;
    }

    &:hover {
        .image {
            opacity: 0.8;
        }

        & .base-button {
            opacity: 0.85;
            display: flex;
        }
    }
}
</style>

// src/components/collection-item/collection-item.jsx
import React from "react";

import "./collection-item.scss";
import BaseButton from "../base/button/base-button";

const CollectionItem = ({ id, name, price, imageUrl }) => (
  <section className="collection-item">
    <div
      className="image"
      style={{
        backgroundImage: `url(${imageUrl})`,
      }}
    />
    <footer className="collection-footer">
      <span className="name">{name}</span>
      <span className="price">{price}</span>
    </footer>
    <BaseButton inverted>Add To Card</BaseButton>
  </section>
);

export default CollectionItem;
