// src/components/SignInUp/SignIn.vue
<template>
    <article class="sign-in">
        <h2>I already have an account</h2>
        <span>Sign in with your email and password.</span>

        <form @submit.prevent="handleSubmit">
            <BaseInput
                id="email"
                type="email"
                name="email"
                required
                v-model="email"
                label="email"
            />

            <BaseInput
                id="password"
                type="password"
                name="password"
                required
                v-model="password"
                label="password"
            />

            <section class="button-group">
                <BaseButton type="submit">
                    Sign In
                </BaseButton>

                <BaseButton @click.prevent="signInWithGoogle" inverted>
                    <GoogleIcon /> Google
                </BaseButton>
            </section>
        </form>
    </article>
</template>

<script>
import BaseButton from '@/components/Base/BaseButton';
import BaseInput from '@/components/Base/BaseInput';
import GoogleIcon from '@/components/Base/GoogleIcon';

import { auth, signInWithGoogle } from '@/firebase/firebase.utils';

export default {
    name: 'SignIn',
    components: {
        BaseButton,
        BaseInput,
        GoogleIcon,
    },
    data() {
        return { email: '', password: '' };
    },
    methods: {
        async handleSubmit() {
            await auth
                .signInWithEmailAndPassword(this.email, this.password)
                .catch(error => console.log(error));

            this.email = '';
            this.password = '';
        },
        signInWithGoogle,
    },
};
</script>

<style lang="postcss" scoped>
.sign-in {
    width: 380px;
    display: flex;
    flex-direction: column;

    & .title {
        margin: 10px 0;
    }

    & .button-group {
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 0.3rem;
        gap: 0.3rem;
    }
}
</style>

// src/components/sign-in/sign-in.jsx
import React from "react";

import "./sign-in.scss";
import BaseInput from "../base/input/base-input";
import BaseButton from "../base/button/base-button";

import { signInWithGoogle, auth } from "../../firebase/firebase.utils";

export default class SignIn extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      email: "",
      password: "",
    };
  }

  handleSubmit = async (e) => {
    e.preventDefault();

    const { email, password } = this.state;

    try {
      await auth.signInWithEmailAndPassword(email, password);
      this.setState({ email: "", password: "" });
    } catch (error) {
      console.log(error);
    }
  };

  handleChange = (e) => {
    const { value, name } = e.target;

    this.setState({ [name]: value });
  };

  render() {
    const { email, password } = this.state;

    return (
      <article className="sign-in">
        <h2>I already have an account</h2>
        <span>Sign in with your email and password.</span>

        <form onSubmit={this.handleSubmit}>
          <BaseInput
            id="email"
            type="email"
            name="email"
            required
            value={email}
            handleChange={this.handleChange}
            label="email"
          />

          <BaseInput
            id="password"
            type="password"
            name="password"
            required
            value={password}
            handleChange={this.handleChange}
            label="password"
          />

          <section className="button-group">
            <BaseButton type="submit">
              Sign In
            </BaseButton>

            <BaseButton onClick={signInWithGoogle} isGoogleSignIn>
              Sign in with Google
            </BaseButton>
          </section>
        </form>
      </article>
    );
  }
}
