// src/components/SignInUp/SignIn.vue
<template>
    <article class="sign-in">
        <h2>I already have an account</h2>
        <span>Sign in with your email and password.</span>

        <form @submit.prevent="handleSubmit">
            <BaseInput
                id="email"
                type="email"
                name="email"
                required
                v-model="email"
                label="email"
            />

            <BaseInput
                id="password"
                type="password"
                name="password"
                required
                v-model="password"
                label="password"
            />

            <section class="button-group">
                <BaseButton type="submit">
                    Sign In
                </BaseButton>

                <BaseButton @click.prevent="signInWithGoogle" inverted>
                    <GoogleIcon /> Google
                </BaseButton>
            </section>
        </form>
    </article>
</template>

<script>
import BaseButton from '@/components/Base/BaseButton';
import BaseInput from '@/components/Base/BaseInput';
import GoogleIcon from '@/components/Base/GoogleIcon';

import { signInWithGoogle } from '@/firebase/firebase.utils';

export default {
    name: 'SignIn',
    components: {
        BaseButton,
        BaseInput,
        GoogleIcon,
    },
    data() {
        return { email: '', password: '' };
    },
    methods: {
        handleSubmit() {},
        signInWithGoogle,
    },
};
</script>

<style lang="postcss" scoped>
.sign-in {
    width: 380px;
    display: flex;
    flex-direction: column;

    & .title {
        margin: 10px 0;
    }

    & .button-group {
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 0.3rem;
        gap: 0.3rem;
    }
}
</style>

// src/components/sign-in/sign-in.component.jsx
import React from 'react'
import BaseButton from '../base-button/base-button.component'
import FormInput from '../form-input/form-input.component'

import { signInWithGoogle } from '../../firebase/firebase.utils'

import './sign-in.styles.scss'

class SignIn extends React.Component {
    constructor(props) {
        super(props)
    
        this.state = {
            email: '',
            password: '',
        }
    }

    handleSubmit = e => {
        e.preventDefault()

        this.setState({ email: '', password: ''})
    }

    handlechange = e => {
        const { value, name } = e.target

        this.setState({ [name]: value })
    }
    
    render() {
        return (
            <div className="sign-in">
                <h2>I already have an account</h2>
                <span>Sign in with your email and password</span>

                <form action="" onSubmit={this.handleSubmit}>
                    <FormInput 
                        type="email" 
                        name="email" 
                        id="sign-in-email" 
                        value={this.state.email} 
                        handleChange={this.handlechange} 
                        label='email' 
                        required 
                    />
                    <FormInput 
                        type="password" 
                        name="password"
                        id="sign-in-password" 
                        value={this.state.password} 
                        handleChange={this.handlechange} 
                        label='password' 
                        required 
                    />

                    <div className="button-group">
                        <BaseButton type="submit">Submit</BaseButton>
                        <BaseButton 
                            isGoogleSignIn
                            onClick={(e) => {
                                e.preventDefault()
                                signInWithGoogle()
                            }}
                        >
                            Sign in with Google
                    </BaseButton>
                    </div>
                </form>
            </div>
        )
    }
}

export default SignIn
