// src/pages/shop/Shop.component.jsx
import React from 'react'
import { SHOP_DATA } from '../../SHOP_DATA'

import CollectionPreview from '../../components/collection-preview/collection-preview.component'

export default class ShopPage extends React.Component {
    constructor(props) {
        super(props)

        this.state = {
            collections: [
                ...SHOP_DATA
            ]
        }
    }

    render() {
        const { collections} = this.state
        return (
            <div className='shop-page'>
                {
                    collections.map(({id, ...collection}) => (
                        <CollectionPreview key={id} {...collection}/>
                    ))
                }
            </div>
        )
    }
}

// src/views/Shop.vue
<template>
    <main>
        <CollectionPreview
            v-for="{ id, ...collectionData } in shopData"
            :key="id"
            :collection="collectionData"
        />
    </main>
</template>

<script>
import SHOP_DATA from '@/api/shop-data.js';

import CollectionPreview from '@/components/Shop/CollectionPreview';

export default {
    name: 'Shop',
    components: {
        CollectionPreview,
    },
    data() {
        return {
            shopData: SHOP_DATA,
        };
    },
};
</script>
