// src/components/header/header.jsx
import React from "react";
import { Link } from "react-router-dom";
import { connect } from "react-redux";
import { auth } from "../../firebase/firebase.utils";

import { ReactComponent as Logo } from "../../assets/logo.svg";

import "./header.scss";
import CartIcon from "../cart-icon/cart-icon";

const Header = ({ currentUser }) => (
  <header className="header">
    <Link className="logo-container" to="/">
      <Logo className="logo" />
    </Link>
    <nav className="options">
      <Link className="option" to="/shop">
        Shop
      </Link>
      <Link className="option" to="/contact">
        Contact
      </Link>
      {currentUser ? (
        <button className="option" onClick={() => auth.signOut()}>
          Sign Out
        </button>
      ) : (
        <Link className="option" to="/sign-in">
          Sign In
        </Link>
      )}
      <CartIcon />
    </nav>
  </header>
);

const mapStateToProps = (state) => ({
  currentUser: state.user.currentUser,
});

export default connect(mapStateToProps)(Header);

// src/components/Nav/Header.vue
<template>
    <header class="header">
        <router-link class="logo-container" to="/">
            <Logo class="logo" />
        </router-link>
        <nav class="options">
            <router-link class="option" to="/shop">
                Shop
            </router-link>
            <router-link class="option" to="/contact">
                Contact
            </router-link>

            <!-- Sign in / Sign out -->
            <button v-if="currentUser" class="option" @click="signOut">
                Sign Out
            </button>
            <router-link v-else class="option" to="/sign-in">
                Sign In
            </router-link>

            <CartIcon />
        </nav>
        <!-- <Cart /> -->
    </header>
</template>

<script>
import Logo from '@/components/Logo';
import CartIcon from '@/components/Nav/CartIcon';

import { auth } from '@/firebase/firebase.utils';

export default {
    name: 'Header',
    components: {
        Logo,
        CartIcon,
    },
    computed: {
        currentUser() {
            return this.$store.state.currentUser;
        },
    },
    methods: {
        signOut() {
            auth.signOut();
        },
    },
};
</script>

<style lang="postcss" scoped>
.header {
    height: 70px;
    width: 100%;
    display: flex;
    justify-content: space-between;
    margin-bottom: 25px;
    line-height: 1.2rem;
    position: relative;

    & .logo-container {
        height: 100%;
        width: 70px;

        & .logo {
            width: 100%;
            height: auto;
        }
    }

    & .options {
        width: 50%;
        height: 100%;
        display: flex;
        align-items: flex-end;
        justify-content: flex-end;
        font-size: 1rem;

        & button.option {
            height: 100%;
            line-height: 1.2rem;
            font-size: 1rem;
            font-family: inherit;
            background-color: transparent;
            border: none;
            display: flex;
            align-items: flex-end;
        }

        & .option {
            padding: 10px 15px;
            text-transform: uppercase;
            cursor: pointer;
        }
    }
}
</style>
